apiVersion: v1
kind: Service
metadata:
  name: pathology-service
  namespace: node-pathology
  labels:
    app: pathology-node
spec:
  type: ClusterIP
  selector:
    app: pathology-node
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
