apiVersion: v1
kind: Service
metadata:
  name: pinn-service
  namespace: central-pinn
  labels:
    app: pinn-server
spec:
  type: ClusterIP
  selector:
    app: pinn-server
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
