apiVersion: v1
kind: Service
metadata:
  name: clinical-service
  namespace: node-clinical
  labels:
    app: clinical-node
spec:
  type: ClusterIP
  selector:
    app: clinical-node
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
